default:
  navigation:
    - title: Mujeres
      subtitle: Categorias
      url: /t/women
      items:
        - :title: Faldas
          :url: /t/women/skirts
        - :title: Vestidos
          :url: /t/women/dresses
        - :title: Camisas y Blusas
          :url: /t/women/shirts-and-blouses
        - :title: Suéteres
          :url: /t/women/sweaters
        - :title: Tops y camisetas
          :url: /t/women/tops-and-t-shirts
        - :title: Chaquetas y abrigos
          :url: /t/women/jackets-and-coats
      promo_banners:
        - subtitle: Nueva colección
          title: Verano 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Ofertas especiales
          title: Obtenga hasta un 30% de descuento
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Hombres
      subtitle: Categorias
      url: /t/men
      items:
        - :title: Camisas
          :url: /t/men/shirts
        - :title: Camisetas
          :url: /t/men/t-shirts
        - :title: Suéteres
          :url: /t/men/sweaters
        - :title: Chaquetas y abrigos
          :url: /t/men/jackets-and-coats
      promo_banners:
        - subtitle: Nueva colección
          title: Verano 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Ofertas especiales
          title: Obtenga hasta un 30% de descuento
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Ropa de deporte
      subtitle: Categorias
      url: /t/sportswear
      items:
        - :title: Tops
          :url: /t/sportswear/tops
        - :title: Sudaderas
          :url: /t/sportswear/sweatshirts
        - :title: Pantalones
          :url: /t/sportswear/pants
      promo_banners:
        - subtitle: Nueva colección
          title: Verano 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Ofertas especiales
          title: Obtenga hasta un 30% de descuento
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
